# numpy 起步

## numpy 简介
量化分析的工作涉及到大量的数值运算，一个高效方便的科学计算工具是必不可少的。NumPy是一个功能强大的Python库，主要用于对多维数组执行计算。NumPy这个词来源于两个单词-- Numerical和Python。NumPy提供了大量的库函数和操作。这类数值计算广泛用于以下任务：
- 一个强大的N维数组对象。
- 有用的线性代数，傅里叶变换和随机数功能。如数值积分、微分、内插、外推等。
- 除了明显的科学用途外，NumPy还可以用作通用数据的高效多维容器。例如：机器学习模型、数字图像处理和计算机图形学等。

## NumPy 经典资源

- [NumPy官网](https://numpy.org/)
- [知乎: CS231n课程笔记翻译：Python Numpy教程](https://zhuanlan.zhihu.com/p/20878530)
- [程序员虾说: NumPy 系列教程](http://www.ysir308.com/archives/category/tutorial/NumPy-tutorial)

## NumPy 中的数组

NumPy提供的最重要的数据结构是NumPy数组对象。NumPy数组配备了大量的函数和运算符，是目前最流行的高性能数组计算库。

In [12]:
import numpy as np 
vector = np.array([1, 2, 3, 4, 5]) 
print('array vector: \n',vector)
print(vector.shape)

vector = np.zeros((5))
print('zeros vector: \n',vector)

vector = np.random.random((5))
print('random vector: \n',vector)

# dot, sum, min, max, cumsum
vector = np.arange(10)
print('vector.sum(): \n',vector.sum())   # >>>45
print('vector.min(): \n',vector.min())   # >>>0
print('vector.max(): \n',vector.max())   # >>>9
print('vector.cumsum(): \n',vector.cumsum()) # >>>[ 0  1  3  6 10 15 21 28 36 45]

array vector: 
 [1 2 3 4 5]
(5,)
zeros vector: 
 [0. 0. 0. 0. 0.]
random vector: 
 [0.59762528 0.57345133 0.5707989  0.46930127 0.62413438]
vector.sum(): 
 45
vector.min(): 
 0
vector.max(): 
 9
vector.cumsum(): 
 [ 0  1  3  6 10 15 21 28 36 45]


## NumPy 中的运算操作

NumPy向量或者矩阵，能够在数组上执行加减乘除数学运算。

In [13]:
import numpy as np 
matrix_a = np.array([[10.0, 20.0], [30.0, 40.0]]) 
matrix_b = np.array([[50.0, 60.0], [70.0, 80.0]]) 
print ('matrix.sum(): \n',matrix_a + matrix_b)
print ('matrix.sub(): \n',matrix_a - matrix_b)
print ('matrix.mul(): \n',matrix_a * matrix_b)
print ('matrix.div(): \n',matrix_a / matrix_b)

matrix.sum(): 
 [[ 60.  80.]
 [100. 120.]]
matrix.sub(): 
 [[-40. -40.]
 [-40. -40.]]
matrix.mul(): 
 [[ 500. 1200.]
 [2100. 3200.]]
matrix.div(): 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]
